<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="LoanProcessorWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/LoanProcessorWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/LoanProcessorWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://loanprocessor.me.org/">
    <import location="http://localhost:8080/LoanProcessor/LoanProcessor?WSDL" namespace="http://loanprocessor.me.org/"/>
    <plnk:partnerLinkType name="LoanProcessorLinkType">
        <plnk:role name="LoanProcessorRole" portType="ns:LoanProcessor"/>
    </plnk:partnerLinkType>
</definitions>
